import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

// The sidebar is generated from the docs folder. Order is set with
// `sidebar_position` in each page and `_category_.json` in each folder.
// Pages marked `draft: true` show in `npm start` but are left out of builds.
const sidebars: SidebarsConfig = {
  docsSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
